begin
  conn = PGconn.connect("localhost", 5432, "" , "", db_name, postgres_username, postgres_password)
  # Do some stuff
rescue PG::ConnectionBad => e
  # There seems to be a bug in PG::ConnectionBad where the error message is doubled.  Get only a single error message
  puts e
  theDoubledMsg = e.to_s
  theSingleMsg = theDoubledMsg.split("\n")[0]
  # See https://stackoverflow.com/questions/2823748/how-do-i-add-information-to-an-exception-message-in-ruby
  raise $!, theSingleMsg, $!.backtrace
rescue Exception => e
  puts e
  raise # reraise exception
ensure
  conn.close if conn
end
